### PR TITLE
:bug: Handle an unavailable API

### LINKED ISSUE #204: Handle the API service being down
Currently if the API is not available the site breaks and doesn't handle
the exception causing it to not show the 'tech fault' page

### PR DESCRIPTION
**Pull request by st3v3nhunt**
Replaces #205 
Fixes #204

### CODE REVIEW

**Comment by st3v3nhunt** [comment]
Arrgh. Still got the bithound check in there!

File: test/globalHooks.js [hunk 1]
```diff
@@ -19,11 +19,12 @@ before('global setup', () => {
 
   nock('https://api.postcodes.io')
     .get(`/postcodes/${ls27ue}`)
-    .times(4)
+    .times(5)
     .reply(200, ls27ueResponse);
 });
 
 after('Check all nocks have been called', () => {
+  console.log(nock.pendingMocks());
```
Comment (neilbmclaughlin) [inline test/globalHooks.js]: Did you intend for this to be left in?

Comment (st3v3nhunt) [inline test/globalHooks.js]: Yeah, I thought it was useful to have the output easily accessed when the tests were running.
